server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }

    # /api/ 경로로 오는 요청은 내부 도커 네트워크의 백엔드 컨테이너로 전달
    location /api/ {
        proxy_pass http://domain1-backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
